apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep-name
  namespace: my-app
  labels:
    app: app-dep-label 
spec:
  selector:
    matchLabels:
      app: app-in-deployment
  replicas: 3
  template:
    metadata:
      labels:
       app: app-in-deployment
    spec:
      containers:
      - name: app-pod-in-dep
        image: 328460808357.dkr.ecr.us-east-1.amazonaws.com/a1-app:v1.0
        env:
        - name: DBHOST
          value: 10.244.0.28
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: babak
        ports:
        - name: employee-ptname
          containerPort: 6666
          protocol: TCP