apiVersion: v1
kind: Pod
metadata:
  name: employees-pod-name
  namespace: my-app
  labels:
    app: employees-pod-name
    Owner: babak
spec:
  containers:
    - name: employees-container-name
      image: 328460808357.dkr.ecr.us-east-1.amazonaws.com/a1-app:v1.0
      env:
        - name: DBHOST
          value: 10-244-0-5.my-db.pod.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: babak
      ports:
        - name: employee-ptname
          containerPort: 8080
          protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
