apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod-name
  namespace: my-db
  labels:
    app: mysql-pod-label
    owner: babak  
spec:
  containers:
    - name: mysql-container-name
      image: 328460808357.dkr.ecr.us-east-1.amazonaws.com/a1-db:v1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "babak"
      ports:
        - name: mysql-port-name
          containerPort: 3306
          protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
