apiVersion: v1
kind: Service
metadata:
  name: nodeport-db-name
  namespace: my-db
  labels:
    app: nodeport-db-label
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: app-db-label